spring.application.name=quizgenai

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/quizgenai
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
#Gemini API
gemini.api.key=
gemini.model=gemini-3.6-flash

#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gokukali723@gmail.com
spring.mail.password=
app.mail.from-name=QuizGenAI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true